"""empty message

Revision ID: 01522c504a3c
Revises: e50120081b4d
Create Date: 2025-08-03 12:05:17.101172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01522c504a3c'
down_revision = 'e50120081b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_price', sa.Float(), nullable=False))
        batch_op.drop_column('_final_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_final_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('final_price')

    # ### end Alembic commands ###
