"""empty message

Revision ID: 02551e810d28
Revises: d5b9ff4648fe
Create Date: 2025-09-06 18:39:17.874559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02551e810d28'
down_revision = 'd5b9ff4648fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aesthetician', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('aesthetician', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
