"""slot capacity added

Revision ID: 0ba0f9a766dc
Revises: 
Create Date: 2025-11-01 18:09:52.466406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ba0f9a766dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_capacity', sa.Integer(), nullable=True))

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('walk_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDeleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walk_in', schema=None) as batch_op:
        batch_op.drop_column('isDeleted')

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_column('slot_capacity')

    # ### end Alembic commands ###
