"""empty message

Revision ID: 14797cae5cd0
Revises: b96517726bf8
Create Date: 2025-08-23 12:38:12.239140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14797cae5cd0'
down_revision = 'b96517726bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='discount_type_enum'), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discounted_price', sa.Float(), nullable=False))
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('original_price')
        batch_op.drop_column('final_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('original_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('discount_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('discounted_price')
        batch_op.drop_column('discount')
        batch_op.drop_column('discount_type')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
