"""empty message

Revision ID: 1a1c17d19493
Revises: 
Create Date: 2025-11-04 17:54:57.892606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1c17d19493'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_in',
    sa.Column('walk_in_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_initial', sa.CHAR(length=1), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('walk_in_id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('walk_in_id', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('aesthetician_id', sa.String(length=255), nullable=True),
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('service_rating', sa.Float(), nullable=True),
    sa.Column('branch_rating', sa.Float(), nullable=True),
    sa.Column('aesthetician_rating', sa.Float(), nullable=True),
    sa.Column('service_comment', sa.Text(), nullable=True),
    sa.Column('branch_comment', sa.Text(), nullable=True),
    sa.Column('aesthetician_comment', sa.Text(), nullable=True),
    sa.Column('customer_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('service_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('price_snapshot', sa.Integer(), nullable=False),
    sa.Column('is_sale_snapshot', sa.Boolean(), nullable=False),
    sa.Column('category_snapshot', sa.String(length=255), nullable=False),
    sa.Column('discount_type_snapshot', sa.Enum('percentage', 'fixed', name='discount_type_enum'), nullable=True),
    sa.Column('discount_snapshot', sa.Float(), nullable=True),
    sa.Column('discounted_price_snapshot', sa.Float(), nullable=True),
    sa.Column('aesthetician_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('is_pro_snapshot', sa.Boolean(), nullable=False),
    sa.Column('branch_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('voucher_code_snapshot', sa.String(length=255), nullable=True),
    sa.Column('voucher_discount_type_snapshot', sa.Enum('percentage', 'fixed', name='discount_type_enum'), nullable=True),
    sa.Column('voucher_discount_amount_snapshot', sa.Float(), nullable=True),
    sa.Column('duration_snapshot', sa.Integer(), nullable=True),
    sa.Column('voucher_code', sa.String(length=255), nullable=True),
    sa.Column('final_payment_method', sa.Enum('cash', 'e-wallet', 'bank-transfer', 'credit-card', 'debit-card', 'xendit', name='payment_method_enum'), nullable=False),
    sa.Column('to_pay', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('completed', 'partial', 'pending', name='payment_status_enum'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('cancelled', 'completed', 'on-process', 'waiting', 'pending', name='appointment_status_enum'), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['aesthetician_id'], ['aesthetician.aesthetician_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['voucher_code'], ['voucher.voucher_code'], ),
    sa.ForeignKeyConstraint(['walk_in_id'], ['walk_in.walk_in_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('walk_in')
    # ### end Alembic commands ###
