"""empty message

Revision ID: 1b45cbde2002
Revises: 2d8b1f49b821
Create Date: 2025-09-30 13:04:08.608489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b45cbde2002'
down_revision = '2d8b1f49b821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('down_payment_status', sa.Enum('completed', 'pending', 'cancelled', name='payment_status_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('down_payment_status')

    # ### end Alembic commands ###
