"""empty message

Revision ID: 24f1f908ce5e
Revises: 
Create Date: 2025-08-02 10:10:41.555708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f1f908ce5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('voucher_code', sa.String(length=255), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('voucher_code')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('walk_in_id', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('aesthetician_id', sa.String(length=255), nullable=False),
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('service_rating', sa.Float(), nullable=False),
    sa.Column('branch_rating', sa.Float(), nullable=False),
    sa.Column('aesthetician_rating', sa.Float(), nullable=False),
    sa.Column('service_comment', sa.Text(), nullable=True),
    sa.Column('branch_comment', sa.Text(), nullable=True),
    sa.Column('aesthetician_comment', sa.Text(), nullable=True),
    sa.Column('voucher_code', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.Enum('cash', 'e_wallet', 'bank_transfer', name='payment_method_enum'), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('cancelled', 'completed', 'pending', 'waiting', name='status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aesthetician_id'], ['aesthetician.aesthetician_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['walk_in_id'], ['walk_in.walk_in_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('voucher')
    # ### end Alembic commands ###
