"""empty message

Revision ID: 27122b6e621a
Revises: 0ba0f9a766dc
Create Date: 2025-11-01 18:11:32.706723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27122b6e621a'
down_revision = '0ba0f9a766dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.alter_column('slot_capacity',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.alter_column('slot_capacity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
