"""Baseline after reset

Revision ID: 2d8b1f49b821
Revises: 
Create Date: 2025-09-30 09:40:18.579294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8b1f49b821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xendit_invoice_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('xendit_external_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('down_payment_paid_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['xendit_external_id'])

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.alter_column('average_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.alter_column('average_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('down_payment_paid_at')
        batch_op.drop_column('xendit_external_id')
        batch_op.drop_column('xendit_invoice_id')

    # ### end Alembic commands ###
