"""empty message

Revision ID: 31607b6eaed7
Revises: 
Create Date: 2025-08-29 08:47:24.550477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31607b6eaed7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
