"""rating in service and branch added

Revision ID: 3e9dc2e71b28
Revises: c9e4f9ca1d87
Create Date: 2025-06-24 11:39:52.644763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9dc2e71b28'
down_revision = 'c9e4f9ca1d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_rating', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('branch_rating', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('aesthetician_rating', sa.Float(), nullable=False))
        batch_op.drop_column('rating')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avarage_rate', sa.Float(), nullable=False))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avarage_rate', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('avarage_rate')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_column('avarage_rate')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('aesthetician_rating')
        batch_op.drop_column('branch_rating')
        batch_op.drop_column('service_rating')

    # ### end Alembic commands ###
