"""empty message

Revision ID: 3fab30f51171
Revises: 
Create Date: 2025-06-13 18:35:09.450575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fab30f51171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('barangay', sa.String(length=255), nullable=False),
    sa.Column('lot', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.String(length=255), nullable=False),
    sa.Column('role_name', sa.Enum('admin', 'customer', 'owner', name='role_enum'), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('auth',
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('branch',
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('address_id', sa.String(length=255), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('branch_id')
    )
    op.create_table('service',
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('user_role',
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['auth.account_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('service')
    op.drop_table('branch')
    op.drop_table('auth')
    op.drop_table('role')
    op.drop_table('address')
    # ### end Alembic commands ###
