"""walk in appointment feature added

Revision ID: 4958af7d1c06
Revises: 3e9dc2e71b28
Create Date: 2025-06-26 13:03:50.155700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4958af7d1c06'
down_revision = '3e9dc2e71b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_in',
    sa.Column('walk_in_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_initial', sa.CHAR(length=1), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'others', name='sex_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('walk_in_id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walk_in_id', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'walk_in', ['walk_in_id'], ['walk_in_id'])

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('avarage_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('avarage_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('walk_in_id')

    op.drop_table('walk_in')
    # ### end Alembic commands ###
