"""empty message

Revision ID: 5142837904ba
Revises: 
Create Date: 2025-08-02 17:41:12.579643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5142837904ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('appointment_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('walk_in_id', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('aesthetician_id', sa.String(length=255), nullable=False),
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('service_rating', sa.Float(), nullable=False),
    sa.Column('branch_rating', sa.Float(), nullable=False),
    sa.Column('aesthetician_rating', sa.Float(), nullable=False),
    sa.Column('service_comment', sa.Text(), nullable=True),
    sa.Column('branch_comment', sa.Text(), nullable=True),
    sa.Column('aesthetician_comment', sa.Text(), nullable=True),
    sa.Column('voucher_code', sa.String(length=255), nullable=True),
    sa.Column('down_payment_method', sa.Enum('cash', 'xendit', name='payment_method_enum'), nullable=True),
    sa.Column('down_payment', sa.Float(), nullable=False),
    sa.Column('final_payment_method', sa.Enum('cash', 'xendit', name='payment_method_enum'), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('to_pay', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('completed', 'partial', 'pending', name='payment_status_enum'), nullable=False),
    sa.Column('status', sa.Enum('cancelled', 'completed', 'pending', 'waiting', name='appointment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aesthetician_id'], ['aesthetician.aesthetician_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['walk_in_id'], ['walk_in.walk_in_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    # ### end Alembic commands ###
