"""empty message

Revision ID: 5870650a2984
Revises: f72affccf28e
Create Date: 2025-09-02 15:42:59.351390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5870650a2984'
down_revision = 'f72affccf28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint('admin_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'auth', ['account_id'], ['account_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_account_id_fkey', 'auth', ['account_id'], ['account_id'])

    # ### end Alembic commands ###
