"""empty message

Revision ID: 5b682e95463c
Revises: 7c76acc2770a
Create Date: 2025-10-12 09:36:15.820001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b682e95463c'
down_revision = '7c76acc2770a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('slot_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_number', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
