"""empty message

Revision ID: 62b1e906f6d2
Revises: 23333e281179
Create Date: 2025-08-30 12:00:26.149757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b1e906f6d2'
down_revision = '23333e281179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('birthday')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
