"""empty message

Revision ID: 63fadd9140d2
Revises: 
Create Date: 2025-08-25 12:44:33.877684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fadd9140d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('barangay', sa.String(length=255), nullable=False),
    sa.Column('lot', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.String(length=255), nullable=False),
    sa.Column('role_name', sa.Enum('admin', 'customer', 'owner', name='role_enum'), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('voucher',
    sa.Column('voucher_code', sa.String(length=255), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='discount_type_enum'), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('minimum_spend', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('voucher_code')
    )
    op.create_table('walk_in',
    sa.Column('walk_in_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_initial', sa.CHAR(length=1), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'others', name='sex_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('walk_in_id')
    )
    op.create_table('auth',
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('branch',
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('address_id', sa.String(length=255), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('average_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', name='branch_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('branch_id')
    )
    op.create_table('admin',
    sa.Column('admin_id', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_initial', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['auth.account_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('aesthetician',
    sa.Column('aesthetician_id', sa.String(length=255), nullable=False),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_initial', sa.CHAR(length=1), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'others', name='sex_enum'), nullable=False),
    sa.Column('experience', sa.Enum('pro', 'regular', name='experience_enum'), nullable=False),
    sa.Column('average_rate', sa.Float(), nullable=True),
    sa.Column('availability', sa.Enum('available', 'working', 'off-duty', 'break', name='availability_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.PrimaryKeyConstraint('aesthetician_id')
    )
    op.create_table('service',
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('branch_id', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_sale', sa.Boolean(), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='discount_type_enum'), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('discounted_price', sa.Float(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('average_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('middle_initial', sa.CHAR(length=1), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['auth.account_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_role',
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['auth.account_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'role_id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('walk_in_id', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('aesthetician_id', sa.String(length=255), nullable=False),
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('service_rating', sa.Float(), nullable=True),
    sa.Column('branch_rating', sa.Float(), nullable=True),
    sa.Column('aesthetician_rating', sa.Float(), nullable=True),
    sa.Column('service_comment', sa.Text(), nullable=True),
    sa.Column('branch_comment', sa.Text(), nullable=True),
    sa.Column('aesthetician_comment', sa.Text(), nullable=True),
    sa.Column('voucher_code', sa.String(length=255), nullable=True),
    sa.Column('down_payment_method', sa.Enum('cash', 'xendit', name='payment_method_enum'), nullable=True),
    sa.Column('down_payment', sa.Float(), nullable=False),
    sa.Column('final_payment_method', sa.Enum('cash', 'xendit', name='payment_method_enum'), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('to_pay', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('completed', 'partial', 'pending', name='payment_status_enum'), nullable=False),
    sa.Column('status', sa.Enum('cancelled', 'completed', 'pending', 'waiting', name='appointment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aesthetician_id'], ['aesthetician.aesthetician_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['voucher_code'], ['voucher.voucher_code'], ),
    sa.ForeignKeyConstraint(['walk_in_id'], ['walk_in.walk_in_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('user_role')
    op.drop_table('user')
    op.drop_table('service')
    op.drop_table('aesthetician')
    op.drop_table('admin')
    op.drop_table('branch')
    op.drop_table('auth')
    op.drop_table('walk_in')
    op.drop_table('voucher')
    op.drop_table('role')
    op.drop_table('address')
    # ### end Alembic commands ###
