"""empty message

Revision ID: 6f565d144c1d
Revises: b280b1c3b82d
Create Date: 2025-11-01 18:56:38.625279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f565d144c1d'
down_revision = 'b280b1c3b82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_snapshot', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('duration_snapshot')

    # ### end Alembic commands ###
