"""empty message

Revision ID: 772284d6a775
Revises: 27122b6e621a
Create Date: 2025-11-01 18:41:34.781926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '772284d6a775'
down_revision = '27122b6e621a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('appointment_xendit_external_id_key', type_='unique')
        batch_op.drop_column('down_payment_method')
        batch_op.drop_column('down_payment_status')
        batch_op.drop_column('down_payment')
        batch_op.drop_column('down_payment_paid_at')
        batch_op.drop_column('xendit_external_id')
        batch_op.drop_column('xendit_invoice_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xendit_invoice_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('xendit_external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('down_payment_paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('down_payment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('down_payment_status', postgresql.ENUM('completed', 'pending', 'cancelled', 'partial', name='payment_status_enum'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('down_payment_method', postgresql.ENUM('cash', 'e-wallet', 'bank-transfer', 'credit-card', 'debit-card', 'xendit', name='payment_method_enum'), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('appointment_xendit_external_id_key', ['xendit_external_id'])

    # ### end Alembic commands ###
