"""empty message

Revision ID: 804b3d5839a4
Revises: bba43033f4bc
Create Date: 2025-09-12 17:41:02.936107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '804b3d5839a4'
down_revision = 'bba43033f4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_discount_type_snapshot', sa.Enum('percentage', 'fixed', name='discount_type_enum'), nullable=True))
        batch_op.add_column(sa.Column('voucher_discount_amount_snapshot', sa.Float(), nullable=True))
        batch_op.alter_column('discounted_price_snapshot',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('voucher_discount_type')
        batch_op.drop_column('voucher_discount_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('voucher_discount_type', postgresql.ENUM('percentage', 'fixed', name='discount_type_enum'), autoincrement=False, nullable=True))
        batch_op.alter_column('discounted_price_snapshot',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('voucher_discount_amount_snapshot')
        batch_op.drop_column('voucher_discount_type_snapshot')

    # ### end Alembic commands ###
