"""empty message

Revision ID: 834a9b87e632
Revises: e2619dce0b2d
Create Date: 2025-07-31 16:10:00.132569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834a9b87e632'
down_revision = 'e2619dce0b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aesthetician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aesthetician', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
