"""empty message

Revision ID: 986bc547e441
Revises: d1ea5172bbc7
Create Date: 2025-08-22 18:19:12.045477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986bc547e441'
down_revision = 'd1ea5172bbc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('middle_initial', sa.String(length=255), nullable=False))
        batch_op.drop_column('admin_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('middle_initial')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
