"""empty message

Revision ID: a391d0b52251
Revises: 3fab30f51171
Create Date: 2025-06-13 19:10:30.212936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a391d0b52251'
down_revision = '3fab30f51171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aesthetician',
    sa.Column('aesthetician_id', sa.String(length=255), nullable=False),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_initial', sa.CHAR(length=1), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'others', name='sex_enum'), nullable=True),
    sa.Column('experience', sa.Enum('pro', 'regular', name='experience_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.PrimaryKeyConstraint('aesthetician_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('middle_initial', sa.CHAR(length=1), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['auth.account_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.String(length=255), nullable=True),
    sa.Column('aesthetician_id', sa.String(length=255), nullable=True),
    sa.Column('service_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('cancelled', 'completed', 'pending', 'waiting', name='status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aesthetician_id'], ['aesthetician.aesthetician_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('appointment')
    op.drop_table('user')
    op.drop_table('aesthetician')
    # ### end Alembic commands ###
