"""empty message

Revision ID: a9cfd46fdabe
Revises: c1b4cde63931
Create Date: 2025-06-14 15:07:16.791332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cfd46fdabe'
down_revision = 'c1b4cde63931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.String(length=255), nullable=False))
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['branch_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
