"""empty message

Revision ID: abb0fe04d17e
Revises: 27b3e04a2c86
Create Date: 2025-08-29 09:35:01.279873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb0fe04d17e'
down_revision = '27b3e04a2c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_id', sa.String(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(), server_default=sa.text("nextval('otp_id_seq'::regclass)"), autoincrement=False, nullable=False))
        batch_op.drop_column('otp_id')

    # ### end Alembic commands ###
