"""empty message

Revision ID: b96517726bf8
Revises: 
Create Date: 2025-08-22 18:51:42.322256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96517726bf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('voucher_code', sa.String(length=255), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='discount_type_enum'), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('minimum_spend', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('voucher_code')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('walk_in_id', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('aesthetician_id', sa.String(length=255), nullable=False),
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('service_rating', sa.Float(), nullable=True),
    sa.Column('branch_rating', sa.Float(), nullable=True),
    sa.Column('aesthetician_rating', sa.Float(), nullable=True),
    sa.Column('service_comment', sa.Text(), nullable=True),
    sa.Column('branch_comment', sa.Text(), nullable=True),
    sa.Column('aesthetician_comment', sa.Text(), nullable=True),
    sa.Column('voucher_code', sa.String(length=255), nullable=True),
    sa.Column('down_payment_method', sa.Enum('cash', 'xendit', name='payment_method_enum'), nullable=True),
    sa.Column('down_payment', sa.Float(), nullable=False),
    sa.Column('final_payment_method', sa.Enum('cash', 'xendit', name='payment_method_enum'), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('to_pay', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('completed', 'partial', 'pending', name='payment_status_enum'), nullable=False),
    sa.Column('status', sa.Enum('cancelled', 'completed', 'pending', 'waiting', name='appointment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aesthetician_id'], ['aesthetician.aesthetician_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['voucher_code'], ['voucher.voucher_code'], ),
    sa.ForeignKeyConstraint(['walk_in_id'], ['walk_in.walk_in_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('middle_initial', sa.String(length=255), nullable=False))
        batch_op.drop_column('admin_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('middle_initial')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('appointment')
    op.drop_table('voucher')
    # ### end Alembic commands ###
