"""empty message

Revision ID: bba43033f4bc
Revises: e368531a6d53
Create Date: 2025-09-12 16:52:16.379831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba43033f4bc'
down_revision = 'e368531a6d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_snapshot', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('aesthetician_name_snapshot', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_pro_snapshot', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('is_pro_snapshot')
        batch_op.drop_column('aesthetician_name_snapshot')
        batch_op.drop_column('category_snapshot')

    # ### end Alembic commands ###
