"""Make aesthetician_id and aesthetician_name_snapshot nullable

Revision ID: c272f40a4c0e
Revises: 6f565d144c1d
Create Date: 2025-11-01 19:31:38.627805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c272f40a4c0e'
down_revision = '6f565d144c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('aesthetician_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('aesthetician_name_snapshot',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('aesthetician_name_snapshot',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('aesthetician_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
