"""empty message

Revision ID: d5b9ff4648fe
Revises: 89b3c93b999d
Create Date: 2025-09-06 18:29:15.966862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b9ff4648fe'
down_revision = '89b3c93b999d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aesthetician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDeleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isDeleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_column('isDeleted')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isDeleted')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('isDeleted')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_column('isDeleted')

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_column('isDeleted')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('isDeleted')

    with op.batch_alter_table('aesthetician', schema=None) as batch_op:
        batch_op.drop_column('isDeleted')

    # ### end Alembic commands ###
