"""empty message

Revision ID: e368531a6d53
Revises: 6934d7c9a1a9
Create Date: 2025-09-12 16:20:19.284764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e368531a6d53'
down_revision = '6934d7c9a1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_discount_type', sa.Enum('percentage', 'fixed', name='discount_type_enum'), nullable=True))
        batch_op.add_column(sa.Column('voucher_discount_amount', sa.Float(), nullable=True))
        batch_op.alter_column('voucher_code_snapshot',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('original_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('voucher_code_snapshot',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('voucher_discount_amount')
        batch_op.drop_column('voucher_discount_type')

    # ### end Alembic commands ###
