"""empty message

Revision ID: e50120081b4d
Revises: 
Create Date: 2025-08-03 11:16:58.243049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50120081b4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_in',
    sa.Column('walk_in_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_initial', sa.CHAR(length=1), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'others', name='sex_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('walk_in_id')
    )
    op.create_table('aesthetician',
    sa.Column('aesthetician_id', sa.String(length=255), nullable=False),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_initial', sa.CHAR(length=1), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'others', name='sex_enum'), nullable=False),
    sa.Column('experience', sa.Enum('pro', 'regular', name='experience_enum'), nullable=False),
    sa.Column('average_rate', sa.Float(), nullable=True),
    sa.Column('availability', sa.Enum('available', 'working', 'off-duty', 'break', name='availability_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.PrimaryKeyConstraint('aesthetician_id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('walk_in_id', sa.String(length=255), nullable=True),
    sa.Column('branch_id', sa.String(length=255), nullable=False),
    sa.Column('aesthetician_id', sa.String(length=255), nullable=False),
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('service_rating', sa.Float(), nullable=True),
    sa.Column('branch_rating', sa.Float(), nullable=True),
    sa.Column('aesthetician_rating', sa.Float(), nullable=True),
    sa.Column('service_comment', sa.Text(), nullable=True),
    sa.Column('branch_comment', sa.Text(), nullable=True),
    sa.Column('aesthetician_comment', sa.Text(), nullable=True),
    sa.Column('voucher_code', sa.String(length=255), nullable=True),
    sa.Column('down_payment_method', sa.Enum('cash', 'xendit', name='payment_method_enum'), nullable=True),
    sa.Column('down_payment', sa.Float(), nullable=False),
    sa.Column('final_payment_method', sa.Enum('cash', 'xendit', name='payment_method_enum'), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('to_pay', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('completed', 'partial', 'pending', name='payment_status_enum'), nullable=False),
    sa.Column('status', sa.Enum('cancelled', 'completed', 'pending', 'waiting', name='appointment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aesthetician_id'], ['aesthetician.aesthetician_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['voucher_code'], ['voucher.voucher_code'], ),
    sa.ForeignKeyConstraint(['walk_in_id'], ['walk_in.walk_in_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('aesthetician')
    op.drop_table('walk_in')
    # ### end Alembic commands ###
