"""empty message

Revision ID: f122121b8d51
Revises: 3af3577f8cb5
Create Date: 2025-08-29 12:51:41.606068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f122121b8d51'
down_revision = '3af3577f8cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_constraint('auth_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.create_unique_constraint('auth_email_key', ['email'])

    # ### end Alembic commands ###
